repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # https://python.plainenglish.io/how-to-improve-your-python-code-style-with-pre-commit-hooks-e7fe3fd43bfa
      - id: check-yaml
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        exclude: ^(docs/)
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
          ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "--dev", "-f", "requirements.txt", "-o", "requirements.txt" ]
