[tool.poetry]
name = "pyexample"
version = "0.1.0"
description = "Coding example!"
authors = ["Viktor Kurti <aplikat@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.0"
commitizen = "^2.42.1"
pylint = "^2.17.0"


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [
    "pyproject.toml:version"
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
