GUI_URL = "https://www.saucedemo.com/"
API_URL = "https://reqres.in"
GET_LIST_USERS = "@format {this.API_URL}/api/users?page=2"
GET_SINGLE_USER = "@format {this.API_URL}/api/users/2"
GET_SINGLE_USER_NOT_FOUND = "@format {this.API_URL}/api/users/23"
POST_CREATE = "@format {this.API_URL}/api/users"
WRONG = "@format {this.API_URL}/wrongbcbcbcbcbcbcb"
DELAY = 5
